### ISSUE TITLE
it does not working

### ISSUE THREAD

**Issue by ShuLianjun** [Arthaey/anki-cloze-blanks#10]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/shulj/Library/Application Support/Anki2/addons/Cloze_Blanks.py", line 46, in clozeEachWordForExistingCards
    _forExistingCards(u"Make each word into a cloze for ALL cards?", _clozeEachWord)
  File "/Users/shulj/Library/Application Support/Anki2/addons/Cloze_Blanks.py", line 52, in _forExistingCards
    nids = mw.col.models.nids(cloze)
  File "anki/models.pyc", line 202, in nids
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by chriad** [comment]
I get a similar error

Traceback (most recent call last):
  File "C:\Users\chriad\AppData\Roaming\Anki2\addons\Cloze_Blanks.py", line 43, in addClozeBlanksToExistingCards
    _forExistingCards(u"Add blanks to ALL cloze cards?", _addClozeBlanksToNotes)
  File "C:\Users\chriad\AppData\Roaming\Anki2\addons\Cloze_Blanks.py", line 52, in _forExistingCards
    nids = mw.col.models.nids(cloze)
  File "anki\models.py", line 202, in nids
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Arthaey** [comment]
This error would happen if you don't have a "Cloze" model. Have you renamed the default Cloze model?

(I've updated the addon with commit # cb6ccca7 to handle this case slightly better, but it can't do much more if it can't figure out which is the Cloze model.)
