### ISSUE TITLE
Cloze Blanks

### ISSUE THREAD

**Issue by zaviazun** [Arthaey/anki-cloze-blanks#7]
Hi. What's up?
I found your add-on - Cloze Blanks https://ankiweb.net/shared/info/546020849 and I like the idea, but unfortunately it doesn't work. 
If it possible, may you edit the code? Thanks!

Traceback (most recent call last):
File "C:\Users\user\Documents\Anki\addons\Cloze_Blanks.py", line 43, in addClozeBlanksToExistingCards
_forExistingCards(u"Add blanks to ALL cloze cards?", _addClozeBlanksToNotes)
File "C:\Users\user\Documents\Anki\addons\Cloze_Blanks.py", line 52, in _forExistingCards
nids = mw.col.models.nids(cloze)
File "anki\models.py", line 202, in nids
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Arthaey** [comment]
Does the latest version still have this problem?

**Comment by Arthaey** [comment]
Please reopen if you see this problem again.
